# Generated by Django 3.0.5 on 2021-06-08 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20210607_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       verbose_name='Дата публикации отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(
                help_text='Оценка произведения от 1 до 10', validators=[
                    django.core.validators.MinValueValidator(1,
                                                             message='Минимальный рейтинг: 1'),
                    django.core.validators.MaxValueValidator(10,
                                                             message='Максимальный рейтинг: 10')],
                verbose_name='Рейтинг'),
        ),
    ]
