# Generated by Django 3.0.5 on 2021-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210610_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, db_column='description', max_length=2000, verbose_name='Биография'),
        ),
    ]
